### ISSUE TITLE
cd linux-like functionality

### ISSUE THREAD

**Issue by GReaperEx** [Piorjade/cLinux#15]
This is kind-of like a feature request.

Normally:
- when given no arguments, cd jumps to the initial directory of the current user.
- when given "-" specifically, cd jumps back to the previous working directory( error if it's the first one ).

How is _G handled in cLinux? Can it be used to declare shell-wide or system-wide environment variables or do you have some other mechanism in place instead?

If you could clarify these things for me, I could implement the change for you.

**Comment by Overflwn** [comment]
@GReaperEx 
Well to clarify one thing: "shell-wide" should be in cLinux the same as "system-wide", because you cannot manipulate anything above the "shell-coroutine-layer" (which are the services)......well except libraries, which get loaded before shell....
Anyway, to answer your question: _G is passed over to everything and everyone... that is, if we talk about STOCK cLinux using the normal commandline, of course.

EDIT: Yeah I'd love to see people requesting other features and even trying to help me :)

**Comment by Overflwn** [comment]
Oh yeah if you need some information, I have some handy functions for you to be used to implement the first request:
```lua
local username, hashedPassword = lib.perm.getCurrentUser()
--This returns the username and the HASHED password of the CURRENTLY LOGGED-IN user
```
With this you can basically implement request#1 (Btw it IS ALREADY implemented, just enter "cd ~", but this is handled by the commandline, which replaces 
> ~

with the user-home-directory...but hey, you can implement request#1 directly in the cd program :) )

Regarding the second request, this would REALLY need _G... so yeah... I hope I clarified some things 👍

**Comment by GReaperEx** [comment]
I'm almost done, but getCurrentUser() is actually inside "lib.perm.permission", FYI. Is this how you wanted to have it or should I wait for a fix?

**Comment by Overflwn** [comment]
@GReaperEx
Oh yeah this example is wrong, it is supposed to be lib.perm.permission.blah

:P
