### ISSUE TITLE
Can't figure out how to load custom libraries

### ISSUE THREAD

**Issue by GReaperEx** [Piorjade/cLinux#16]
I put my library inside lib/. It says that it loads it OK at each boot. But... whenever I try to call any of its functions, it says I tried to index nil. In other words, either the library isn't actually loaded or it's lost during the _G manipulation inside shell.run?

I tried to pinpoint the location where the table is either deleted or not loaded but the structure of this program is too convoluted for me...

**Comment by Overflwn** [comment]
Wait I'll look into that

**Comment by Overflwn** [comment]
@GReaperEx 
Ok you got the lib-system wrong. :) (I'll cover that in the Wiki tomorrow)

The libraries get loaded differently at boot.
Example library which works:
```lua
local test = {}
test.testprint = function()
  print("Hello")
end

--put the whole test-table in _G.lib.myLibrary
_putLib("myLibrary", test) --first argument is the how to name it and second is the function/table/variable

--put only the test.testprint function directly in _G.myFunction
_put("myFunction", test.testprint) --first argument is the how to name it and second is the function/table/variable
```

So basically the OS executes the code of your library so that means your LIBRARY has to put itself into _G, which is why I created the _put and _putLib functions for users.
Why didn't I make it like os.loadAPI? (like you expected it to be) Well there is no PARTICULAR reason but I think it helped me handling passing things over to services AND you have the ability to actually name the API in _G (os.loadAPI uses the name of the file, which I don't really like).

I hope I could help you out :)

**Comment by GReaperEx** [comment]
Oh, I see, now it makes sense! Thanks for explaining it.
